### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference [recovered]

### ISSUE THREAD

**Issue by temarusanov** [netbirdio/kubernetes-operator#21]
```
2025-04-03T11:51:20Z    ERROR   Reconciler error        {"controller": "nbroutingpeer", "controllerGroup": "netbird.io", "controllerKind": "NBRoutingPeer", "NBRoutingPeer": {"name":"router","namespace":"netbird"}, "namespace": "netbird", "name": "router", "reconcileID": "de1794fa-01de-4e99-a88f-4da13709b5f6", "error": "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"}
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).reconcileHandler
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:332
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).processNextWorkItem
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:279
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller[...]).Start.func2.2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.20.0/pkg/internal/controller/controller.go:240
```

```
  values:
    ingress:
      enabled: true
    router:
      enabled: true
    netbirdAPI:
      key: REDACTED
    managementURL: https://netbird.REDACTED:443
    cluster:
      name: REDACTED
```
