### ISSUE TITLE
Helm Feature Request: Support default Labels for all resources

### ISSUE THREAD

**Issue by mhartmann-jaconi** [netbirdio/kubernetes-operator#41]
In a company GKE cluster there is a validation webhook installed which checks for specific labels to be present on all created K8s resources. (Fyi: Those labels are used to determine the team, owning and managing those resources). An example could look like
```
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    acme_com_managed_by: platform-engineering
    acme_com_owned_by: release-engineering
```
We can not install the helm chart on the cluster, without the support for such default labels on all resources.

**Feature Request**
Build a helm value for default resource annotations, which get automatically applied to all created K8s resources
